SHELL := /bin/bash

-include Makefile.common

.PHONY: format
format:: venv
	. "$(_VENV_ACTIVATE)" && \
		isort . && black .

.PHONY: test
test:: venv
	echo "Executing pytest"
	@. "$(_VENV_ACTIVATE)" && python -m pytest -v $(_DIR_STRUCTURE)/tests/


.PHONY: install
install:: pre-install
	echo "Installing requirements."; \
		. "$(_VENV_ACTIVATE)" && pip install -r requirements.txt


.PHONY: lint
lint:: venv
	. "$(_VENV_ACTIVATE)" && \
		prospector