name: Bump Version

on:
  workflow_dispatch:

jobs:
  bump:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make install

      - name: Bump Version
        run: make bump

      - name: Commit Version
        run: make all
