name: CD

on:
   workflow_dispatch:

env:
  _PROJECT: ${{ github.event.repository.name }}
  _USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: make install

      - name: bump version
        run: make bump

      - name: authorise git
        run: make authorise

      - name: commit all changes
        run: make all

  publish_release:
    runs-on: ubuntu-latest
    needs: [ bump_version ]
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: make install

      - name: authorise git
        run: make authorise USER=${{ github.actor }} EMAIL="filip.szmid@gmail.com"

      - name: tag new version
        run: make tag

      - name: update changelog
        run: make changelog UNRELEASED=`cat VERSION`

      - name: commit all changes
        run: make all

      - name: publish release
        run: make release
