name: CI-CD

on:
   workflow_dispatch:

env:
  _PROJECT: ${{ github.event.repository.name }}
  _USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Install prerequisites
##        run: sudo make install-allure #no dollar sign
#        run: make brew-allure

      - name: Install dependencies
        run: make install

      - name: Run check
        run: make test
  lint:
    name: Static code checkers
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: Run check
      run: make lint

  format:
    name: Formatter
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make install

      - name: Run check
        run: make format

  build:
    name: Build Docker
    needs: [ test, lint, format ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker build
        run: make build

      - name: docker up
        run: make up

  deploy_testing:
    name: Testing
    needs: [ build ]
    environment:
      name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo rm -rf ${{ github.event.repository.name }}/
            git clone git@github.com:${{ github.actor }}/${{ github.event.repository.name }}.git
            cd ${{ github.event.repository.name }}/
            make down-volumes
            make build
            make up ALLOWED_HOSTS=${{ secrets.TESTING_HOST_IP }} SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          host: ${{ secrets.TESTING_HOST_IP }}
          user: ubuntu
          key: ${{ secrets.TESTING_SSH_PRIVATE_KEY }}

  bump_version:
    name: Bump Version
    environment:
      name: Production
    runs-on: ubuntu-latest
    needs: [ deploy_testing ]
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: make install

      - name: bump version
        run: make bump

      - name: authorise git
        run: make authorise USER=${{ github.actor }} EMAIL="${{ github.actor }}@users.noreply.github.com"

      - name: commit all changes
        run: make all

  publish_release:
    name: Publish Release
    runs-on: ubuntu-latest
    needs: [ bump_version ]
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: make install

      - name: authorise git
        run: make authorise USER=${{ github.actor }} EMAIL="${{ github.actor }}@users.noreply.github.com"

      - name: tag new version
        run: make tag

      - name: update changelog
        run: make changelog UNRELEASED=`cat VERSION`

      - name: commit all changes
        run: make all

      - name: publish release
        run: make release

  deploy_prod:
    name: Production
    needs: [ publish_release ]
    environment:
      name: Production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: fifsky/ssh-action@master
        with:
          command: |
            sudo rm -rf ${{ github.event.repository.name }}/
            git clone git@github.com:${{ github.actor }}/${{ github.event.repository.name }}.git
            cd ${{ github.event.repository.name }}/
            make down-volumes
            make build
            make up ALLOWED_HOSTS=${{ secrets.PRODUCTION_HOST_IP }} SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}
          host: ${{ secrets.PRODUCTION_HOST_IP }}
          user: ubuntu
          key: ${{ secrets.PRODUCTION_SSH_PRIVATE_KEY }}