name: CI-CD

on:
   workflow_dispatch:

env:
  _PROJECT: ${{ github.event.repository.name }}
  _USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Install prerequisites
##        run: sudo make install-allure #no dollar sign
#        run: make brew-allure

      - name: Install dependencies
        run: make install

      - name: Run check
        run: make test
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: make install

    - name: Run check
      run: make lint

  format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: make install

      - name: Run check
        run: make format

  build:
    name: docker
    needs: [ test, lint, format ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker build
        run: make build

      - name: docker up
        run: make up

  bump_version:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: make install

      - name: bump version
        run: make bump

      - name: authorise git
        run: make authorise USER=${{ github.actor }} EMAIL="${{ github.actor }}@users.noreply.github.com"

      - name: commit all changes
        run: make all

  publish_release:
    runs-on: ubuntu-latest
    needs: [ bump_version ]
    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: make install

      - name: authorise git
        run: make authorise USER=${{ github.actor }} EMAIL="${{ github.actor }}@users.noreply.github.com"

      - name: tag new version
        run: make tag

      - name: update changelog
        run: make changelog UNRELEASED=`cat VERSION`

      - name: commit all changes
        run: make all

      - name: publish release
        run: make release
