name: CI-Integrate

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  _PROJECT: ${{ github.event.repository.name }}
  _USER: ${{ github.actor }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

#      - name: Install prerequisites
##        run: sudo make install-allure #no dollar sign
#        run: make brew-allure

      - name: install packages
        run: make install

      - name: run tests
        run: make test
  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install packages
      run: make install

    - name: run linter
      run: make lint

  format:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install packages
        run: make install

      - name: run formatter
        run: make format

  build:
    name: docker
    needs: [ test, lint, format ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: docker build
        run: make build

      - name: docker up
        run: make up

